<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5jqkqxj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5jqkqxj/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5jqkqxj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5jqkqxj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5jqkqxj\appProdProjectContainer([
    'container.build_hash' => '5jqkqxj',
    'container.build_id' => '16c2bd79',
    'container.build_time' => 1636970933,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5jqkqxj');
